# Generated by Django 5.2.5 on 2026-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
