# Generated by Django 5.2.3 on 2025-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
