# Generated by Django 5.2.3 on 2025-07-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiqueryhistory',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
