# Generated by Django 5.2.6 on 2026-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
