# Generated by Django 5.2.3 on 2025-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
