# Generated by Django 5.2.6 on 2026-03-27 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.IntegerField()),
                ('scheme_name', models.CharField(max_length=300)),
                ('scheme_category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='interested', max_length=20)),
                ('clicked_apply', models.BooleanField(default=False)),
                ('self_marked_applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'scheme_id')},
            },
        ),
    ]
